[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
protocol = "http"
port = "8000"
domains = ["${SERVICE_NAME}.railway.app"] 